### ISSUE TITLE
limestone performance of specific tenants doubles build time

### ISSUE THREAD

**Issue by ssbarnea** [ansible/project-config#334]
I now have some proof that some tenants doubles the build time from ~1h to 2h per job:

- https://dashboard.zuul.ansible.com/t/ansible/build/0c7c2c14133941538e7e259d470face4
- https://dashboard.zuul.ansible.com/t/ansible/build/56456a78b2754a2e990d1992e9418cf7

Apparently this is what they have in common:
```
      nodepool:
        az: us-slc-1
        cloud: limestone
        host_id: 0cfb34ab4f8d5f4de345d6879fbfd3571095d106dd72e218c3ae4c4c
        provider: limestone-us-slc
        region: us-slc
```

@pabelanger ^
